### ISSUE TITLE
Action Items

### ISSUE THREAD

**Issue by fanminshi** [fanminshi/simple-server#1]
- [x] add main.go and create static html file ref: https://github.com/fanminshi/simple-server/pull/2
- [x] add tls artifacts ref: https://github.com/fanminshi/simple-server/pull/3
- [x] add docker build file #4 
- [x] test the server image on kubernetes 
- [x] allow simple server to take in tls secret. #7 
- [x] enable mutual TLS #9 
- [x] update the readmes with mutual TLS description
